import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js/+esm'

class Guest {
	constructor(name, isChild) {
		this.Name = name;
		this.Dinner = null;
		this.Attending = null;
		this.RestrictionsNote = null;
		this.IsChild = isChild;
	}
}

class Reservation {
	constructor(plusOneAllowed, passcode, guestNames, childNames) {
		this.id = crypto.randomUUID(); // autogenerated
		this.created_at = new Date();
		this.can_add_plus_one = plusOneAllowed;
		this.not_attending_note = null;
		this.plus_one = new Guest(null);
		this.guests = [];
		guestNames.forEach(name => this.guests.push(new Guest(name, false)));
		if (childNames != null) { childNames.forEach(name => this.guests.push(new Guest(name, true))) };
		this.passcode = passcode;
	}
}

export class RSVPBackend {
	constructor() {
		this.supabase = createClient('https://pvlfpzfbdmgegmvaqhsc.supabase.co', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB2bGZwemZiZG1nZWdtdmFxaHNjIiwicm9sZSI6ImFub24iLCJpYXQiOjE2NTI0MDc5NDIsImV4cCI6MTk2Nzk4Mzk0Mn0.lGYQHdB3qmP7aoPpL21wW9x6gy-M5E3BhAXMS3uDPF4');
	}
	async SearchForReservation(passcode) {
		let { data: reservation, error } = await this.supabase
			.from('reservation')
			.select('*')
			.eq("passcode", passcode);

		console.log(reservation, error);
		if (error) {
			return Promise.reject("I had a database failure. Please try again later.");
		}

		if (reservation.length === 0) {
			return Promise.reject("No invitation found. Try entering your secret passcode again.");
		}

		return Promise.resolve(reservation[0]);
	}

	async SaveReservation(reservation) {
		const { data, error } = await this.supabase
			.from('reservation')
			.update(reservation)
			.eq('passcode', reservation.passcode);

		if (error) {
			return Promise.reject("There was a big problem updating things");
		}

		return Promise.resolve(data);
	}

	async DeleteAllData() {
		const { data, error } = await this.supabase
			.from('reservation')
		  	.delete()
		  	.eq('can_add_plus_one', false);

		 if (error) { alert(error.message) };

		const { data1, error1 } = await this.supabase
			.from('reservation')
		  	.delete()
		  	.eq('can_add_plus_one', true);

		 if (error1) { alert(error1.message) };
	}

	async UploadRSVPData() {
		const peopleToUpload = [
			new Reservation(true, "super_secret_passcode", ["Nathan Lafferty", "Emily Werdal"]),
			new Reservation(false, "racecar", ["Michael Lafferty", "Debbie Lambert", "Kamren Lambert", "Kassidy Lambert"]),
			new Reservation(false, "florida", ["Andrew Lafferty", "Sarah Lafferty"], ["Lilly Lafferty", "Jackson Lafferty", "Leah Lafferty"]),
			new Reservation(true, "pdiggity", ["Seth Pope"]),
			new Reservation(true, "2010", ["Ian Harris"]),
			new Reservation(false, "slainte", ["Trevor Andersen", "Leah Pope"]),
			new Reservation(false, "travelor", ["Kurry Watson", "Abbie Watson"]),
			new Reservation(false, "🥝", ["Kiwi Sullivan", "Breanna Sullivan"]),
			new Reservation(false, "ridethebus", ["Nicholas Clobes", "Kat Clobes"]),
			new Reservation(false, "busparty", ["Nick Frazier", "Ella Vasquez"]),
			new Reservation(true, "aoe2champ", ["Nick Schneider"]),
			new Reservation(true, "mexico", ["Chase Hill"]),
			new Reservation(true, "westcoast", ["Jordan White"]),
			new Reservation(true, "diablo", ["Josh Maline"]),
			new Reservation(false, "starcraft", ["Craig Maline", "Cherie Maline"]),
			new Reservation(true, "auntdeb", ["Aunt Deb"]),
			new Reservation(true, "grandpa", ["Grandpa"]),
			new Reservation(true, "mom", ["Mary Werdal"]),
			new Reservation(true, "1werdalkidleft", ["James Werdal"]),
			new Reservation(false, "aspen", ["Meg Anderson", "Eric Anderson"]),
			new Reservation(false, "isuisu", ["Peter Benzoni", "Pavithra Lakshmi Suresh"]),
			new Reservation(true, "apt405", ["Spencer Peterson"]),
			new Reservation(false, "catinthehat", ["Nicole Morris", "Chris Morris"], ["Daniel Morris", "Carter Morris"]),
			new Reservation(false, "gobulldogs", ["Jenna Gut", "Brian Gut"]),
			new Reservation(false, "zellmer", ["Tammy Zellmer", "Dave Zellmer"]),
			new Reservation(false, "cvocvo", ["Christopher Van Oort", "Michelle Van Oort"]),
			new Reservation(false, "secretcave", ["Benjamin Sissel", "Brittany Sissel"]),
			new Reservation(false, "scotland", ["Zach Pederson", "Jess Pederson"]),
			new Reservation(false, "boattrip", ["Joe Dohn", "Mel Dillon"]),
			new Reservation(false, "inception", ["Jordan Krohn", "Paula Coryn"]),
			new Reservation(true, "gotswole", ["Adam Guzan"]),
			new Reservation(false, "lorenzo", ["Christopher Waters", "Abby"]),
		];

		const { data, error } = await this.supabase
			.from('reservation')
			.insert(peopleToUpload);

		 if (error) { alert(error.message) };

		return Promise.resolve(data);
	}
}